version: '3.8'

services:
  backend:
    build:
      context: ./production-management
    container_name: production-backend
    ports:
      - "8080:8080"  # backend exposé en 8081 sur ta machine
    networks:
      - production-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-production
    container_name: production-frontend
    ports:
      - "4200:80"  # Angular (ou autre frontend) visible sur http://localhost:4200
    networks:
      - production-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: production-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: production_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - production-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: production-phpmyadmin
    restart: always
    ports:
      - "8082:80"  # phpMyAdmin accessible sur http://localhost:8082
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - production-network

volumes:
  db-data:

networks:
  production-network:
    driver: bridge
