version: '3.8'

services:
  backend:
    build:
      context: ./production
    container_name: production-backend
    ports:
      - "8080:8080"
    networks:
      - production-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-production
    container_name: production-frontend
    ports:
      - "4200:80"
    networks:
      - production-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: production-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: production_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - production-network

volumes:
  db-data:

networks:
  production-network:
    driver: bridge
